name: social-preview-doctor
description: Emulate social crawlers and validate OG/Twitter metadata
inputs:
  url:
    description: URL to inspect
    required: true
  baseline:
    description: Baseline file path
    required: false
    default: og-baseline.json
  update_baseline:
    description: Update baseline instead of comparing
    required: false
    default: "false"
  user_agent:
    description: linkedin | twitter | facebook
    required: false
    default: linkedin
  json:
    description: Output JSON
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - run: npm install
      shell: bash
    - run: npm run build
      shell: bash
    - run: node dist/index.js ${{ inputs.url }} --user-agent ${{ inputs.user_agent }} ${{ inputs.json == 'true' && '--json' || '' }} --baseline ${{ inputs.baseline }} ${{ inputs.update_baseline == 'true' && '--update-baseline' || '' }}
      shell: bash
